### ISSUE TITLE
PyPI works; but tarball URL is still broken

### ISSUE THREAD

**Issue by CrazyPython** [OpenCageData/python-opencage-geocoder#12]
It seems like you haven't created the new release on github yet. The new update URL goes to `Not Found` again, although the download table has the correct URL.

https://github.com/OpenCageData/python-opencage-geocoder/tarball/1.1.3

Don't forget, the installation works, it's just that the "Download URL" doesn't work.

**Comment by mtmail** [comment]
Ah, I didn't see that link. That works now and I updated the release documentation to make sure it doesn't happen again.
