### ISSUE TITLE
Check for quota "402 Payment Required"

### ISSUE THREAD

**Issue by theconor** [OpenCageData/python-opencage-geocoder#13]
The geocoder.py current checks only for HTTP response 429 "Too many requests" to raise the quota exceeded error.  However, for me at least, the code OpenCage sends me is 402 "Payment required".  The python module does not detect this alternative code and just gives me empty results list.

Ideal fix would be to make this check more robust - check the JSON as well as the HTTP header. Here is a sample:
  "rate":{"limit":2500,"remaining":0,"reset":1439683200},"results":[],"status":{"code":402,"message":"quota exceeded"},
  X-RateLimit-Remaining:"0"

Note another handy feature would be the ability to query the geocoder object for the number of calls remaining and the reset time.  This would allow the client to prioritise data to be parsed.

**Comment by mtmail** [comment]
Thanks a lot for the bug report!
I released version 1.1.4 which correctly looks for HTTP response 402.

**Comment by ChristianRohde** [comment]
Hi, I got used to download my data from garmin with gcexport.py using python 2.7. Since several days I get the Payment Required Error: 

> connecting to Garmin Connect... Done.
> Requesting Login ticket... Done. Ticket=ST-0301676-ml9OFtXzu6KfhaBfyStY-cas
> Authenticating... Done.
> [ERROR] Failed to reach url https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=10, error: HTTP Error 402: Payment Required

Now I am confused: is this a software problem on my side or did garmin change the way I can download my data?
