### ISSUE TITLE
KeyNameError: building key in the components portion has become "unknown"

### ISSUE THREAD

**Issue by wangchongyu86** [OpenCageData/python-opencage-geocoder#20]
When requesting the reverse geocoding information via https://api.opencagedata.com/geocode/v1/, in the components portion, the previsous key "building" now became "unknown".
![Capture](https://user-images.githubusercontent.com/32739505/59561823-30652400-9057-11e9-808a-42608efb41f1.JPG)

**Comment by freyfogle** [comment]
Hi,

this has nothing to do with the python module, that is the value returned by the geocoding API.

**Comment by freyfogle** [comment]
This has now been fixed in the API, thanks for letting us know about this error
