### ISSUE TITLE
from opencage.geocoder import OpenCageGeocode not found 

### ISSUE THREAD

**Issue by shubham-kumarpandey** [OpenCageData/python-opencage-geocoder#37]
Traceback (most recent call last):
  File "C:\Users\hp\numberlocation\main.py", line 19, in <module>
    from opencage.geocoder import OpenCageGeoCoder
ImportError: cannot import name 'OpenCageGeoCoder' from 'opencage.geocoder' (C:\Users\hp\python 310\lib\site-packages\opencage\geocoder.py)

**Comment by mtmail** [comment]
Please provide more details besides copy&pasting an error message.

(If "numberlocation" is a project to find out the location of a phone number: opencage geocoder cannot do that and any youtube video claiming it can are wrong.)
