### ISSUE TITLE
Support request formats: xml and geojson

### ISSUE THREAD

**Issue by nate-bush** [OpenCageData/python-opencage-geocoder#38]
The [documentation lists 3 alternative request formats](https://opencagedata.com/api#request): xml, geojson, and google-v3-json (although the last one is set to be deprecated). It would be helpful if the developer could choose their desired format when initializing `OpenCageGeocode`.

**Comment by mtmail** [comment]
Is which situation is this helpful? The output of the Python library is a Python data structure.
