### ISSUE TITLE
ModuleNotFoundError: No module named 'opencage.geocoders'; 'opencage' is not a package

### ISSUE THREAD

**Issue by lemious** [OpenCageData/python-opencage-geocoder#44]
i have already installed opencage and geocode.
Traceback (most recent call last):
  File "C:\Users\92934\PycharmProjects\pythonProject2\numberLocation.py", line 15, in <module>
    from opencage.geocoders import OpenCageGeocode
ModuleNotFoundError: No module named 'opencage.geocoders'; 'opencage' is not a package

**Comment by mtmail** [comment]
For your project you don't have to install anything. `numberLocation.py` will never work because the API cannot locate phone numbers. https://blog.opencagedata.com/post/we-can-not-convert-a-phone-number-into-a-location-sorry

**Comment by mtmail** [comment]
>  from opencage.geocoders import OpenCageGeocode

Should be `opencage.geocoder`, not `opencage.geocoders`
