### ISSUE TITLE
Not on PyPi?

### ISSUE THREAD

**Issue by DenisCarriere** [OpenCageData/python-opencage-geocoder#5]
Would it be possible to have this module on PyPi for ease of installation.

```bash
$ pip install opencage
```

**Comment by freyfogle** [comment]
you are right, that is an oversight. As you can possibly tell, we're not python experts. 

We're on it, though likely to be a few days. thanks for reminding us.

**Comment by DenisCarriere** [comment]
No problem! If you ever need any help, just ask away!

**Comment by mtmail** [comment]
Finally, version 1.1. is on pypi. Thanks for pushing!
